name: minisoccer-microservice-app
services:
  order-service:
    container_name: order-service
    # image: terenjit/order-service:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004" 
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json
    