name: minisoccer-microservice-app
services:
  payment-service:
    container_name: payment-service
    image: terenjit/payment-service:${BUILD_NUMBER}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003" 
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json
    