name: minisoccer-microservice-app
services:
  field-service:
    container_name: field-service
    image: terenjit/field-service:${BUILD_NUMBER}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002" 
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json
    