name: minisoccer-microservice-app
services:
  field-service:
    container_name: field-service
    platform: linux/amd64
    image: terenjit/field-service:34
    ports:
      - "8002:8002" 
    env_file:
      - .env