name: minisoccer-microservice-app
services:
  user-service:
    container_name: user-service
    platform: linux/amd64
    image: terenjit/user-service:${BUILD_NUMBER}
    ports:
      - "8001:8001" 
    env_file:
      - .env